# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7f5305011776c0db6440a6bb1d1c0f210b930129a9fdc15bf7202d61aecc364118ca73827c0ad9fad732d99d4122bf1738973d6d4da8171fe8b579ca1ad62da

test:
  secret_key_base: 7a1980885780b2121c001419ccc719b572f207885c6b890d8368efe02df22b28e35727729b05e6b2ac6f0099d763ea795c07fb9f411d8b1170aea0aa710de869

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
